// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMx9vni2tS2E6BvrTrcIXajyrktkClyT0',
    appId: '1:270117527240:web:123fb7986004626857cffd',
    messagingSenderId: '270117527240',
    projectId: 'daily-wages-87775',
    authDomain: 'daily-wages-87775.firebaseapp.com',
    storageBucket: 'daily-wages-87775.appspot.com',
    measurementId: 'G-2Z7P20HJKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJSy0kdZXvMdUd5JoU9LNYJyLvBhzfmpI',
    appId: '1:270117527240:android:5a9e9c57857cff8757cffd',
    messagingSenderId: '270117527240',
    projectId: 'daily-wages-87775',
    storageBucket: 'daily-wages-87775.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnZjuo57IPw3SYV4I0lDbLdc0mAFm16qs',
    appId: '1:270117527240:ios:421b3ef61c7017e657cffd',
    messagingSenderId: '270117527240',
    projectId: 'daily-wages-87775',
    storageBucket: 'daily-wages-87775.appspot.com',
    iosBundleId: 'com.example.dailyWage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnZjuo57IPw3SYV4I0lDbLdc0mAFm16qs',
    appId: '1:270117527240:ios:cb35239b3d886e4757cffd',
    messagingSenderId: '270117527240',
    projectId: 'daily-wages-87775',
    storageBucket: 'daily-wages-87775.appspot.com',
    iosBundleId: 'com.example.dailyWage.RunnerTests',
  );
}
